version: '3.9'

services:
  payara:
    image: payara/server-full:latest
    container_name: front-api
    ports:
      - "8081:8080"
    volumes:
      - ./target/front-api-1.0.0.war:/opt/payara/deployments/front-api.war